ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
]

if settings.DEBUG:
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path

from .views import *

urlpatterns = [
	path('', IndexView.as_view(), name='index'),
	path('category-list/', CategoryListView.as_view(), name='category_list'),
	path('product-detail-<int:product_id>/', product_detail, name='product'),
	path('login/', LoginPage.as_view(), name='login'),
	path('register/', RegisterPage.as_view(), name='register'),
	path('logout/', LogoutPage.as_view(), name='logout'),
	path('add-to-cart/<int:product_id>/', add_to_cart, name='add_to_cart'),
	path('remove-from-cart/<int:product_id>/', remove_from_cart, name='remove_from_cart'),
	path('remove-single/<int:product_id>/', remove_product_for_order_sum, name='remove_single'),
	path('cart/order-sum/', OrderSummaryPage.as_view(), name='order_sum'),
	path('cart/checkout/', CheckOutPage.as_view(), name='checkout'),
	path('cart/payment-procedure/<payment_option>/', PaymentPageForExample.as_view(), name='payment_page'),
	path('favorites/add/<int:product_id>/', add_to_fav, name='add_to_fav'),
	path('favorites/', FavoritesPage.as_view(), name='fav'),
]

main/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.db.models import Sum
from django.urls import reverse

from django_countries.fields import CountryField


TYPE_PRODUCT_LABELS = (
	('P', 'primary'),
	('S', 'secondary'),
	('D', 'danger'),
)

ADDRESS_CHOICES = (
	('B', 'billing'),
	('S', 'shipping'),
)


class UserProfile(models.Model):
	user = models.OneToOneField(User, on_delete=models.CASCADE, verbose_name='Пользователь', related_name='profile')
	stripe_customer_id = models.CharField(max_length=50, blank=True, null=True)
	one_click_purchasing = models.BooleanField(default=False)

	def __str__(self):
		return self.user.username


class ProductCategory(models.Model):
	name = models.CharField(max_length=255, verbose_name='Название категории')
	slug = models.SlugField(max_length=255, verbose_name='URL для категории')

	def __str__(self):
		return self.name

	class Meta:
		verbose_name = 'Категория (продукта)'
		verbose_name_plural = 'Категории (продуктов)'


class ForProductCategory(models.Model):
	name = models.CharField(max_length=255, verbose_name='Название под-категории')
	slug = models.SlugField(max_length=255, verbose_name='URL для под-категории')
	category = models.ForeignKey(ProductCategory, on_delete=models.CASCADE, verbose_name='Категория для под-категории', related_name="pod")

	def __str__(self):
		return self.name

	class Meta:
		verbose_name = 'Под-категория'
		verbose_name_plural = 'Под-категории'


class ImageProductContent(models.Model):
	user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='Пользователь')
	image = models.ImageField(upload_to='product_images/', verbose_name='Фото')

	class Meta:
		verbose_name = 'Фото контент продукта'
		verbose_name_plural = 'Фото контент продуктов'


class Product(models.Model):
	title = models.CharField(max_length=150, verbose_name='Название продукта')
	poster = models.ImageField(upload_to='product_posters/', verbose_name='Постер продукта', blank=True, null=True)
	price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='Цена товара')
	discount_price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='Начальная цена товара')
	category = models.ForeignKey(ForProductCategory, on_delete=models.CASCADE, verbose_name='Категория товара')
	product_type_label = models.CharField(max_length=1, choices=TYPE_PRODUCT_LABELS, verbose_name='Тип редкости')
	slug = models.SlugField(max_length=150, verbose_name='URL для продукта')
	description = models.TextField("Описание товара")
	image_content = models.ManyToManyField(ImageProductContent, blank=True, verbose_name='Фотки продукта')
	product_qt = models.PositiveSmallIntegerField(default=1, verbose_name='Кол-во товара в наличии')

	def __str__(self):
		return self.title

	class Meta:
		verbose_name = 'Продукт'
		verbose_name_plural = 'Продукты'
		ordering = ['-pk']


class OrderProduct(models.Model):
	user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='Пользователь')
	order_status = models.BooleanField(default=False)
	product = models.ForeignKey(Product, on_delete=models.CASCADE, verbose_name='Продукт')
	quantity = models.PositiveSmallIntegerField(default=1, verbose_name='Кол-во продукта для заказа')

	def __str__(self):
		return self.user.username + " " + self.product.title

	def get_total_price(self):
		return self.quantity * self.product.price

	def get_total_discount_price(self):
		return self.quantity * self.product.discount_price

	def get_summ_of_saved_money(self):
		return self.get_total_price() - self.get_total_discount_price()

	def get_price(self):
		if self.product.discount_price:
			return self.get_total_discount_price()
		return self.get_total_price()

	class Meta:
		verbose_name = 'Продукт для заказа'
		verbose_name_plural = 'Продукты для заказов'


class Order(models.Model):
	user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='Пользователь', related_name='orders')
	ref_code = models.CharField(max_length=20, blank=True, null=True)
	products = models.ManyToManyField(OrderProduct)
	start_date = models.DateTimeField(auto_now_add=True)
	ordered_date = models.DateTimeField()
	ordered = models.BooleanField(default=False)
	shipping_address = models.ForeignKey('Address', on_delete=models.SET_NULL, verbose_name="Адрес доставки", related_name='shipping_address', blank=True, null=True)
	billing_address = models.ForeignKey('Address', on_delete=models.SET_NULL, verbose_name="Адрес для выставления счета", related_name='billing_address', blank=True, null=True)
	payment = models.ForeignKey('Payment', on_delete=models.SET_NULL, verbose_name='Платеж', blank=True, null=True)
	coupon = models.ForeignKey('Coupon', on_delete=models.SET_NULL, verbose_name='Купон', blank=True, null=True)
	being_delivered = models.BooleanField(default=False, verbose_name='Достовляется')
	recieved = models.BooleanField(default=False, verbose_name='Получен')
	refund_requested = models.BooleanField(default=False, verbose_name='Запрошен возврат')
	refund_granted = models.BooleanField(default=False, verbose_name='Возврат гарантирован')

	def __str__(self):
		return self.user.username

	def get_total(self):
		total_price = 0
		for order_product in self.products.all():
			total_price += int(order_product.get_total_price())
		if self.coupon:
			total_price -= int(self.coupon.amount)
		return total_price

	class Meta:
		verbose_name = 'Заказ'
		verbose_name_plural = 'Заказы'


class Address(models.Model):
	user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='Пользователь')
	street_address = models.CharField(max_length=100, verbose_name='Адрес улицы')
	apartment_address = models.CharField(max_length=100, verbose_name='Адрес здания')
	county = CountryField(multiple=False)
	zip = models.CharField(max_length=100)
	address_type = models.CharField(max_length=1, choices=ADDRESS_CHOICES)
	default = models.BooleanField(default=False)

	def __str__(self):
		return self.user.username

	class Meta:
		verbose_name = 'Адрес'
		verbose_name_plural = 'Адреса'


class Payment(models.Model):
	stripe_charge_id = models.CharField(max_length=50)
	user = models.ForeignKey(User, on_delete=models.SET_NULL, verbose_name='Пользователь', blank=True, null=True)
	amount = models.FloatField()
	timestamp = models.DateTimeField(auto_now_add=True)

	def __str__(self):
		return self.user.username

	class Meta:
		verbose_name = 'Платеж'
		verbose_name_plural = 'Платежи'


class Coupon(models.Model):
	code = models.CharField(max_length=15)
	amount = models.FloatField()

	def __str__(self):
		return self.code

	class Meta:
		verbose_name = 'Купон'
		verbose_name_plural = 'Купоны'


class Refund(models.Model):
	order = models.ForeignKey(Order, on_delete=models.CASCADE, verbose_name='Заказ')
	reason_for = models.TextField()
	accepted = models.BooleanField(default=False)
	email = models.EmailField()

	def __str__(self):
		return str(self.pk)

	class Meta:
		verbose_name = 'Запрос на возврат'
		verbose_name_plural = 'Запросы на возврат'


class Favorite(models.Model):
	user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name="Владелец")
	fav_products = models.ManyToManyField(Product, blank=True, verbose_name='Продукты')

	def __str__(self):
		return self.user.username

	class Meta:
		verbose_name = 'Избранное'
		verbose_name_plural = 'Избранные'


def userprofile_receiver(sender, instance, created, *args, **kwargs):
	if created:
		userprofile = UserProfile.objects.create(user=instance)


post_save.connect(userprofile_receiver, sender=User)

templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <title>Ecommerce.ru - {% block title %}{% endblock title %}</title>
      {% block extra_head %}{% endblock extra_head %}
  </head>
  <body>

    <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'index' %}">Ecommerce.ru</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Авторизация
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            {% if user.is_authenticated %}
            <li><a class="dropdown-item" href="{% url 'fav' %}">Избранное</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="{% url 'logout' %}">Выйти</a></li>{% else %}
            <li><a class="dropdown-item" href="{% url 'register' %}">Зарегестрироваться</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="{% url 'login' %}">Войти</a></li>
            {% endif %}
          </ul>
        </li>
        {% if user.is_authenticated %}
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Корзина 

            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-basket-fill" viewBox="0 0 16 16">
  <path d="M5.071 1.243a.5.5 0 0 1 .858.514L3.383 6h9.234L10.07 1.757a.5.5 0 1 1 .858-.514L13.783 6H15.5a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-.5.5H15v5a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V9H.5a.5.5 0 0 1-.5-.5v-2A.5.5 0 0 1 .5 6h1.717L5.07 1.243zM3.5 10.5a.5.5 0 1 0-1 0v3a.5.5 0 0 0 1 0v-3zm2.5 0a.5.5 0 1 0-1 0v3a.5.5 0 0 0 1 0v-3zm2.5 0a.5.5 0 1 0-1 0v3a.5.5 0 0 0 1 0v-3zm2.5 0a.5.5 0 1 0-1 0v3a.5.5 0 0 0 1 0v-3zm2.5 0a.5.5 0 1 0-1 0v3a.5.5 0 0 0 1 0v-3z"></path>
</svg>

          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            {% if user.orders.exists %}
            <li><a class="dropdown-item" href="{% url 'order_sum' %}">Итог заказа</a></li>
            {% endif %}
          </ul>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'category_list' %}">Категории</a>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled">@{{user.username}}</a>
        </li>
        {% endif %}
      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

     <div class="mt-5 pt-4">
    {% if messages %}
        {% for message in messages %}
        <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
          {{ message }}
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        {% endfor %}
    {% endif %}
    </div>

    <div class="container mt-3">
      {% block content %}{% endblock content %}
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
  {% block extra_scripts %}{% endblock extra_scripts %}
  </body>
</html>

templates/categories.html
{% extends 'base.html' %}

{% block title %}Категории продуктов{% endblock title %}

{% block content %}

{% for category in categories %}
	<div class="dropdown mb-3" style="display: inline-block;">
  <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
    {{category.name}}
  </button>
  <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
    {% for pod_category in category.pod.all %}
    	<li><a class="dropdown-item" href="#">{{pod_category.name}}</a></li>
    {% empty %}
    	<li><a class="dropdown-item">Еще нет под-категорий</a></li>
    {% endfor %}
  </ul>
</div>
{% endfor %}

{% endblock content %}

templates/chekout.html
{% extends 'base.html' %}

{% block title %}Проверка - завершение покупок{% endblock title %}

{% block content %}

<main >
    <div class="container wow fadeIn">
      <h2 class="my-5 h2 text-center">Форма оформления заказа</h2>
      <div class="row">
        <div class="col-md-8 mb-4">
          <div class="card">
            <form method="POST" class="card-body">
              {% csrf_token %}

              <h3>Адреса доставки</h3>

              <div class='hideable_shipping_form'>

                <div class="md-form mb-5">
                  <input type='text' placeholder='1234 Главная улица' id='shipping_address' name='shipping_address' class='form-control' />
                  <label for="shipping_address" class="">Адрес</label>
                </div>

                <div class="md-form mb-5">
                  <input type='text' placeholder='Apartment or suite' id='shipping_address2' name='shipping_address2' class='form-control' />
                  <label for="shipping_address2" class="">Адрес 2 (необязательно) </label>
                </div>

                <div class="row">
                  <div class="col-lg-4 col-md-12 mb-4">
                    <label for="country">Страна</label>
                    {{ form.shipping_country }}
                    <div class="invalid-feedback">
                      Пожалуйста выберите правильную страну.
                    </div>
                  </div>
                  <div class="col-lg-4 col-md-6 mb-4">
                    <label for="shipping_zip">Почтовый индекс </label>
                    <input type='text' placeholder='Почтовый индекс ' id='shipping_zip' name='shipping_zip' class='form-control' />
                    <div class="invalid-feedback">
                      Требуется почтовый индекс.
                    </div>
                  </div>
                </div>

                <div class="custom-control custom-checkbox">
                  <input type="checkbox" class="custom-control-input" name="same_billing_address" id="same_billing_address">
                  <label class="custom-control-label" for="same_billing_address">Платежный адрес совпадает с моим адресом доставки </label>
                </div>
                <div class="custom-control custom-checkbox">
                  <input type="checkbox" class="custom-control-input" name="set_default_shipping" id="set_default_shipping">
                  <label class="custom-control-label" for="set_default_shipping">Сохранить как адрес доставки по умолчанию </label>
                </div>

              </div>

              {% if default_shipping_address %}
              <div class="custom-control custom-checkbox">
                <input type="checkbox" class="custom-control-input" name="use_default_shipping" id="use_default_shipping">
                <label class="custom-control-label" for="use_default_shipping">Использовать адрес доставки по умолчанию: {{ default_shipping_address.street_address|truncatechars:10 }}</label>
              </div>
              {% endif %}

              <hr>

              <h3>Адреса для выставления счета </h3>

              <div class='hideable_billing_form'>
                <div class="md-form mb-5">
                  <input type='text' placeholder='1234 главная ул' id='billing_address' name='billing_address' class='form-control' />
                  <label for="billing_address" class="">Адрес</label>
                </div>

                <div class="md-form mb-5">
                  <input type='text' placeholder='Apartment or suite' id='billing_address2' name='billing_address2' class='form-control' />
                  <label for="billing_address2" class="">Адрес 2 (необязательно)</label>
                </div>

                <div class="row">
                  <div class="col-lg-4 col-md-12 mb-4">
                    <label for="country">Страна</label>
                    {{ form.billing_country }}
                    <div class="invalid-feedback">
                      Пожалуйста выберите правильную страну.
                    </div>
                  </div>

                  <div class="col-lg-4 col-md-6 mb-4">
                    <label for="billing_zip">Почтовый индекс</label>
                    <input type='text' placeholder='Почтовый индекс' id='billing_zip' name='billing_zip' class='form-control' />
                    <div class="invalid-feedback">
                      Почтовый индекс обязателен.
                    </div>
                  </div>

                </div>

                <div class="custom-control custom-checkbox">
                  <input type="checkbox" class="custom-control-input" name="set_default_billing" id="set_default_billing">
                  <label class="custom-control-label" for="set_default_billing">Сохранить как платежный адрес по умолчанию </label>
                </div>

              </div>

              {% if default_billing_address %}
              <div class="custom-control custom-checkbox">
                <input type="checkbox" class="custom-control-input" name="use_default_billing" id="use_default_billing">
                <label class="custom-control-label" for="use_default_billing">Use default billing address: {{ default_billing_address.street_address|truncatechars:10 }}</label>
              </div>
              {% endif %}
              <hr>

              <h3>Платежная система</h3>

              <div class="d-block my-3">
                {% for value, name in form.fields.payment_option.choices %}
                <div class="custom-control custom-radio">
                  <input id="{{ name }}" name="payment_option" value="{{ value }}" type="radio" class="custom-control-input" required>
                  <label class="custom-control-label" for="{{ name }}">{{ name }}</label>
                </div>
                {% endfor %}
              </div>

              <hr class="mb-4">
              <button class="btn btn-warning btn-lg btn-block" type="submit">продолжить оформление заказа </button>

            </form>

          </div>

        </div>

        <div class="col-md-4 mb-4">
          {% comment %}{% include "order_snippet.html" %}{% endcomment %}
        </div>

      </div>

    </div>
  </main>

{% endblock content %}

templates/favorites.html
{% extends 'base.html' %}

{% block title %}Избранные{% endblock title %}

{% block content %}

	<h3>Продукты - Избранные</h3>

	{% for product in user_fav.fav_products.all %}
	<div class="card mt-3 mb-3" style="width: 18rem; display: inline-block;">
    {% if product.poster %}
  <img src="{{product.poster.url}}" class="card-img-top" alt="...">{% endif %}
  <div class="card-body">
    <h5 class="card-title">{{product.title}}</h5>
    <p class="card-text">{{product.description|truncatechars:50}}</p>
    <p>{{product.price}} RUB</p>
    <a href="{% url 'product' product.pk %}" class="btn btn-outline-dark">Детальней</a>
  </div>
</div>
{% empty %}
У вас еще нет избранных продуктов
	{% endfor %}


{% endblock content %}

templates/index.html
{% extends 'base.html' %}

{% block title %}Главная{% endblock title %}

{% block content %}

	<h3>Главная - Продукты</h3>

	{% for product in products %}
	<div class="card mt-3 mb-3" style="width: 18rem; display: inline-block;">
    {% if product.poster %}
  <img src="{{product.poster.url}}" class="card-img-top" alt="...">{% endif %}
  <div class="card-body">
    <h5 class="card-title">{{product.title}}</h5>
    <p class="card-text">{{product.description|truncatechars:50}}</p>
    <p>{{product.price}} RUB</p>
    <a href="{% url 'product' product.pk %}" class="btn btn-outline-dark">Детальней</a>
  </div>
</div>
	{% endfor %}


{% endblock content %}

templates/login.html
{% extends 'base.html' %}

{% block title %}Вход в аккаунт{% endblock title %}

{% block content %}

<form method='POST'>{% csrf_token %}
  <p>{{form.username}}</p>
  <p>{{form.password}}</p>
  <input style="width: 100%" type="submit" class="btn btn-primary" value="Войти">
</form>

{% endblock content %}

templates/order_summary.html
{% extends 'base.html' %}

{% block title %}Итог заказа{% endblock title %}

{% block content %}

	<h3 class="mb-3">Корзина - Итог заказа</h3>

	<table class="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Название</th>
      <th scope="col">Цена</th>
      <th scope="col">Изначальная цена</th>
      <th scope="col">Кол-во</th>
    </tr>
  </thead>
  <tbody>
  	{% for order_product in order.products.all %}
    <tr>
      <th scope="row">{{forloop.counter}}</th>
      <td>{{order_product.product.title}}</td>
      <td>{{order_product.product.price}} RUB.KOP</td>
      <td>{{order_product.product.discount_price}} RUB.KOP</td>
      <td>{{order_product.quantity}} 
      	<a href="{% url 'add_to_cart' order_product.product.pk %}" class="btn btn-warning">
      		<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-caret-up-fill" viewBox="0 0 16 16">
  <path d="m7.247 4.86-4.796 5.481c-.566.647-.106 1.659.753 1.659h9.592a1 1 0 0 0 .753-1.659l-4.796-5.48a1 1 0 0 0-1.506 0z"></path>
</svg>
      	</a>
      	<a href="{% url 'remove_single' order_product.product.pk %}" class="btn btn-warning">
      		<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-caret-down-fill" viewBox="0 0 16 16">
  <path d="M7.247 11.14 2.451 5.658C1.885 5.013 2.345 4 3.204 4h9.592a1 1 0 0 1 .753 1.659l-4.796 5.48a1 1 0 0 1-1.506 0z"></path>
</svg>
      	</a>
      </td>
    </tr>
    {% endfor %}

  </tbody>
</table>

{% if order.coupon %}
	<h4 class="mt-3">Используется купон для покупки: -{{order.coupon.amount}} RUB.KOP</h4>
{% endif %}

<h3 class="mt-3">Общая цена заказа: {{order.get_total}} RUB</h3>

<div class="btns mt-2" style="display: inline-block;">
	<a href="/" class="btn btn-dark">Продолжить шоппинг</a>
	<a href="{% url 'checkout' %}" class="btn btn-warning">Перейти к оплате</a>
</div>

{% endblock content %}

templates/product_detail.html
{% extends 'base.html' %}

{% block title %}{{product.title}}{% endblock title %}

{% block content %}

  <h3 class="product__title">{{product.title}} <span class="badge bg-secondary">{{product.get_product_type_label_display}}</span></h3>

  {% if product.image_content != None %}<div class="block__for_images"></div>{% endif %}

  <div class="discount_price__and_price" style="display: inline-block;">
    <h4>{{product.price}} {% if product.discount_price != product.price %} | <span><strike>{{product.discount_price}}</strike></span>{% endif %} RUB</h4>
  </div>

  <div class="image__block">
    {% for image_content in product.image_content.all %}
      <img src="{{image_content.image.url}}" width="250" height="250">
    {% endfor %}
  </div>

  <div class="description">
    <h2>Описание продукта</h2>
    {{product.description}}
  </div>

  {% if user.is_authenticated %}
  <div class="buttons mt-2" style="display: inline-block;">
    {% if at_cart == False %}
    <a href="{% url 'add_to_cart' product.pk %}" class="btn btn-primary">Добавить в корзину</a>
    {% else %}
    <a href="{% url 'remove_from_cart' product.pk %}" class="btn btn-danger">Убрать из корзины</a>
    <a href="{% url 'add_to_cart' product.pk %}" class="btn btn-primary">+ кол-во</a>
    {% endif %}
    <a href="{% url 'add_to_fav' product.pk %}" class="btn btn-warning">Добавить / убрать в / из избранное(ых)</a>
  </div>
  {% endif %}

{% endblock content %}

templates/register.html
{% extends 'base.html' %}

{% block title %}Регистрация{% endblock title %}

{% block content %}

<form method='POST'>{% csrf_token %}
  <p>{{form}}</p>
  <input style="width: 100%" type="submit" class="btn btn-primary" value="Зарегестрироваться">
</form>

{% endblock content %}